import { ColorThemeType, PaletteType } from '../types';

export const createLightTheme = (palette: PaletteType): ColorThemeType => ({
  color: {
    primary: palette.primary40,
    primaryContainer: palette.primary90,
    secondary: palette.secondary40,
    secondaryContainer: palette.secondary90,
    tertiary: palette.tertiary40,
    tertiaryContainer: palette.tertiary90,
    surface: palette.neutral99,
    surfaceVariant: palette.neutralVariant90,
    surfaceContainerHighest: palette.neutral90,
    surfaceContainerHigh: palette.neutral92,
    surfaceContainer:  palette.neutral94,
    surfaceContainerLow: palette.neutral96,
    surfaceContainerLowest: palette.neutral100,
    surfaceTintColor: palette.primary40,
    surfaceTint: palette.primary40,
    background: palette.neutral99,
    error: palette.error40,
    errorContainer: palette.error90,
    onPrimary: palette.primary100,
    onPrimaryContainer: palette.primary10,
    onSecondary: palette.secondary100,
    onSecondaryContainer: palette.secondary10,
    onTertiary: palette.tertiary100,
    onTertiaryContainer: palette.tertiary10,
    onSurface: palette.neutral10,
    onSurfaceVariant: palette.neutralVariant30,
    onError: palette.error100,
    onErrorContainer: palette.error10,
    onBackground: palette.neutral10,
    outline: palette.neutralVariant50,
    outlineVariant: palette.neutralVariant80,
    shadow: palette.neutral0,
    inverseSurface: palette.neutral20,
    inverseOnSurface: palette.neutral95,
    inversePrimary: palette.primary80,
    scrim: palette.neutral0,
  },
});
